package principal;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import produtos.FrmProdutos;
import usuarios.FrmUsuarios;
import vendas.FrmCaixa;
import vendas.FrmVendas;

/**
 *
 * @author Marcely
 */
public class MenuPrincipal extends javax.swing.JFrame {

    public MenuPrincipal() {
        initComponents();
        
        try {
            Thread.sleep(100);
            //identificarUsuario();
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public boolean fecharTela(Object obj){
        
        //carrega todos os formulários abertos do sistema no vetor ativo[]
        JInternalFrame ativo[] = carregador.getAllFrames();
        boolean fechado = true;
        int i = 0;
        
        while( i < ativo.length && fechado){
            if (ativo[i] == obj){
                fechado = false;
            }
            i++;
        }
        return fechado;
    }
    
    class Horas implements ActionListener {
        
        @Override
        public void actionPerformed(ActionEvent e){
            Date sistemaHora = new Date();
            String pmAm = "HH:mm:ss a";
            SimpleDateFormat formato = new SimpleDateFormat(pmAm);
            Calendar now = Calendar.getInstance();
            txtHora.setText(String.format(formato.format(sistemaHora), now));
        }        
    }
    
    /*private void identificarUsuario() {
        String nome = Sessao.getUsuario();
        int id = Sessao.armazenarUsuario(nome);
        
        if (id <= 0) {
            JOptionPane.showMessageDialog(null, "Usuário não encontrado",
                    "Erro usuário", JOptionPane.ERROR_MESSAGE);
        } else {
            String query = "SELECT codigo_us FROM usuarios WHERE codigo_us = " + id + ";";
            JOptionPane.showMessageDialog(null, "Número usuário: " + id + "\nNome usuário: " +nome,
                    "Identificação de Usuário", JOptionPane.INFORMATION_MESSAGE);
        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelCabecalho = new javax.swing.JPanel();
        txtHora = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        txtLogOut = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        logouser = new javax.swing.JLabel();
        logodesconect = new javax.swing.JLabel();
        btnInfos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        btnCaixa = new javax.swing.JButton();
        carregador = new principal.Carregador();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ponto de Vendas - Administrador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        painelPrincipal.setPreferredSize(new java.awt.Dimension(1280, 640));
        painelPrincipal.setLayout(new java.awt.BorderLayout());

        painelCabecalho.setBackground(new java.awt.Color(0, 0, 51));
        painelCabecalho.setPreferredSize(new java.awt.Dimension(1280, 125));
        painelCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtHora.setForeground(new java.awt.Color(255, 255, 255));
        txtHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHora.setText("HORA");
        txtHora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painelCabecalho.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 180, -1));

        txtData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtData.setForeground(new java.awt.Color(255, 255, 255));
        txtData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtData.setText("DIA - MES - ANO");
        txtData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painelCabecalho.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 34, 160, -1));

        txtLogOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtLogOut.setForeground(new java.awt.Color(255, 255, 255));
        txtLogOut.setText("DESCONECTAR...");
        txtLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLogOutMouseClicked(evt);
            }
        });
        painelCabecalho.add(txtLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setText("USUARIO");
        painelCabecalho.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 101, -1));

        logouser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logouser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/conectado.png"))); // NOI18N
        painelCabecalho.add(logouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        logodesconect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logodesconect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/desconec.png"))); // NOI18N
        logodesconect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logodesconectMouseClicked(evt);
            }
        });
        painelCabecalho.add(logodesconect, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        btnInfos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInfos.setForeground(new java.awt.Color(255, 255, 255));
        btnInfos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/info.png"))); // NOI18N
        btnInfos.setText("INFORMAÇÕES");
        btnInfos.setBorder(null);
        btnInfos.setContentAreaFilled(false);
        btnInfos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInfos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInfos.setName("btnInfos"); // NOI18N
        btnInfos.setPreferredSize(new java.awt.Dimension(100, 120));
        btnInfos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/info2.png"))); // NOI18N
        btnInfos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInfos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInfosMouseClicked(evt);
            }
        });
        painelCabecalho.add(btnInfos, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, 120));

        btnUsuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/usuario1.png"))); // NOI18N
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.setBorder(null);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setName("btnUsuarios"); // NOI18N
        btnUsuarios.setPreferredSize(new java.awt.Dimension(100, 120));
        btnUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/usuario2.png"))); // NOI18N
        btnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        painelCabecalho.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, 120));

        btnProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProduto.setForeground(new java.awt.Color(255, 255, 255));
        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/produtos.png"))); // NOI18N
        btnProduto.setText("PRODUTOS");
        btnProduto.setBorder(null);
        btnProduto.setContentAreaFilled(false);
        btnProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProduto.setName("btnProduto"); // NOI18N
        btnProduto.setPreferredSize(new java.awt.Dimension(100, 120));
        btnProduto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/produtos2.png"))); // NOI18N
        btnProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });
        painelCabecalho.add(btnProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, 120));

        btnVendas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVendas.setForeground(new java.awt.Color(255, 255, 255));
        btnVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/vendas1.png"))); // NOI18N
        btnVendas.setText("VENDAS");
        btnVendas.setBorder(null);
        btnVendas.setContentAreaFilled(false);
        btnVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVendas.setName("btnVendas"); // NOI18N
        btnVendas.setPreferredSize(new java.awt.Dimension(100, 120));
        btnVendas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/vendas2.png"))); // NOI18N
        btnVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasActionPerformed(evt);
            }
        });
        painelCabecalho.add(btnVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, -1, 120));

        btnCaixa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCaixa.setForeground(new java.awt.Color(255, 255, 255));
        btnCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/caixa.png"))); // NOI18N
        btnCaixa.setText("CAIXA");
        btnCaixa.setBorder(null);
        btnCaixa.setContentAreaFilled(false);
        btnCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCaixa.setName("btnCaixa"); // NOI18N
        btnCaixa.setPreferredSize(new java.awt.Dimension(100, 120));
        btnCaixa.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/caixa2.png"))); // NOI18N
        btnCaixa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixaActionPerformed(evt);
            }
        });
        painelCabecalho.add(btnCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, 120));

        painelPrincipal.add(painelCabecalho, java.awt.BorderLayout.PAGE_START);

        carregador.setName("carregador"); // NOI18N
        painelPrincipal.add(carregador, java.awt.BorderLayout.CENTER);

        getContentPane().add(painelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogOutMouseClicked
        
        int retorno = JOptionPane.showConfirmDialog(this, "Deseja realmente deslogar do sistema?",
                "Encerrar sessão de Administrador", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (retorno == JOptionPane.YES_OPTION){
            this.dispose();
            Login login = new Login();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
        }
        
    }//GEN-LAST:event_txtLogOutMouseClicked

    FrmProdutos produtos;
    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        if (fecharTela(produtos) == true){
            produtos = new FrmProdutos();
            carregador.add(produtos).setLocation(150,3); 
            produtos.show();
        } else {
            JOptionPane.showMessageDialog(this, "A tela já está aberta!!", "Aviso", 2);
            produtos.toFront();
            produtos.show();
        }
    }//GEN-LAST:event_btnProdutoActionPerformed

    FrmCaixa caixa;
    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        if (fecharTela(caixa) == true){
            caixa = new FrmCaixa();
            carregador.add(caixa).setLocation(20,3);
            caixa.show();
        } else {
            JOptionPane.showMessageDialog(this, "A tela já está aberta!!", "Aviso", 2);
            caixa.toFront();
            caixa.show();
        }
    }//GEN-LAST:event_btnCaixaActionPerformed

    FrmVendas vendas;
    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
        if (fecharTela(vendas) == true){
            vendas = new FrmVendas();
            carregador.add(vendas).setLocation(150,3);
            vendas.show();
        } else {
            JOptionPane.showMessageDialog(this, "A tela já está aberta!!", "Aviso", 2);
            vendas.toFront();
            vendas.show();
        }
    }//GEN-LAST:event_btnVendasActionPerformed

    FrmUsuarios usuarios;
    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        //JOptionPane.showMessageDialog(this, "Chegou aqui", "Depurando o código", 2);
        if (fecharTela(usuarios) == true){
            usuarios = new FrmUsuarios();
            //setLocation() <- posiciona o formulário que está sendo chamado, definindo 150 pixels a direita e 3 abaixo
            carregador.add(usuarios).setLocation(150, 6);
            usuarios.show();
        } else { 
            JOptionPane.showMessageDialog(this, "A tela já está aberta!!", "Aviso", 2);
            usuarios.toFront();
            usuarios.show();
        }  
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void logodesconectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logodesconectMouseClicked
        // TODO add your handling code here:
        int retorno = JOptionPane.showConfirmDialog(this, "Deseja realmente sair do sistema?",
                "Encerrar sessão de Administrador", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (retorno == JOptionPane.YES_OPTION){
            this.dispose();
            Login login = new Login();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
        }
    }//GEN-LAST:event_logodesconectMouseClicked

    private void btnInfosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfosMouseClicked
        // TODO add your handling code here:    
        JOptionPane.showMessageDialog(this, "Página em construção!", "Aviso", 2,
                new ImageIcon(getClass().getResource("/imagens/principal/pagina_em_construcao.png")));
    }//GEN-LAST:event_btnInfosMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Data do sistema
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd MMMM yyyy");
        txtData.setText(formato.format(dataSistema));
        
        //Horário do sistema
        Timer horarioSistema = new Timer(100, new MenuPrincipal.Horas());
        horarioSistema.start();
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPrincipal tela = new MenuPrincipal();
                tela.setLocationRelativeTo(null);
                tela.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaixa;
    private javax.swing.JButton btnInfos;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVendas;
    public static principal.Carregador carregador;
    private javax.swing.JLabel logodesconect;
    private javax.swing.JLabel logouser;
    private javax.swing.JPanel painelCabecalho;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtHora;
    private javax.swing.JLabel txtLogOut;
    public static javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
