package usuarios;

import app.bolivia.swing.JCTextField;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Marcely Biguzzi Santello
 */
public class FrmUsuarios extends javax.swing.JInternalFrame {

 
    public FrmUsuarios() {
        initComponents();
        
        tabelaUsuarios.getTableHeader().setDefaultRenderer(new principal.EstiloTabelaHeader());
        tabelaUsuarios.setDefaultRenderer(Object.class, new principal.EstiloTabelaRenderer());
        // puxa um registro armazenado na tabela Usuários no banco de dados
        tabelaUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        limparCampos();

        //Inicialização dos componentes
        cmbSexo.addItemListener(new ItemListener() {

            //Toda vez que o item deste select ou combobox for alterado
            @Override
            public void itemStateChanged(ItemEvent ie) {
                if(cmbSexo.getSelectedItem().equals("SEXO")){
                    lblSexo.setIcon(new ImageIcon(getClass().getResource("/imagens/usuarios/tipousL.png")));
                }
                if (cmbSexo.getSelectedItem().equals("FEMININO")){
                    lblSexo.setIcon(new ImageIcon(getClass().getResource("/imagens/usuarios/feminino.jpg")));
                }
                if (cmbSexo.getSelectedItem().equals("MASCULINO")){
                    lblSexo.setIcon(new ImageIcon(getClass().getResource("/imagens/usuarios/masculino.png")));
                }
            }
        });
        
        cmbTipo.addItemListener(new ItemListener(){

            @Override
            public void itemStateChanged(ItemEvent ie) {
                if(cmbTipo.getSelectedItem().equals("TIPO USUARIO")){
                    lblTipo.setIcon(new ImageIcon(getClass().getResource("/imagens/usuarios/tipousL.png")));   
                }
                if (cmbTipo.getSelectedItem().equals("ADMINISTRADOR")){
                    lblTipo.setIcon(new ImageIcon(getClass().getResource("/imagens/usuarios/administrador.png")));
                }
                if (cmbTipo.getSelectedItem().equals("PADRAO")){
                    lblTipo.setIcon(new ImageIcon(getClass().getResource("/imagens/usuarios/normal.png")));
                }
            }
            
        });
        
        tabelaUsuarios.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                //Se uma das linhas de registros for alterada, então executa a atualização de dados
                if (tabelaUsuarios.getSelectedRow() != -1){
                    atualizarDados();
                    selecionarRegistro = true;
                }
            }
        });
    }
    
    public void atualizarDados(){
        int linha = tabelaUsuarios.getSelectedRow();
        txtCodigo.setText(tabelaUsuarios.getValueAt(linha, 0).toString());
        txtNome.setText(tabelaUsuarios.getValueAt(linha, 1).toString());
        cmbSexo.setSelectedItem(tabelaUsuarios.getValueAt(linha, 2).toString());
        cmbTipo.setSelectedItem(tabelaUsuarios.getValueAt(linha, 3).toString());
        txtSenha.setText(tabelaUsuarios.getValueAt(linha, 4).toString());
        
    }
    
    public void limparCampos(){
        if (tabelaUsuarios.getSelectedRow() > -1){
            tabelaUsuarios.removeRowSelectionInterval(tabelaUsuarios.getSelectedRow(), tabelaUsuarios.getSelectedRow());
        }
        txtCodigo.setText("");
        txtNome.setText("");
        cmbSexo.setSelectedItem("SEXO");
        cmbTipo.setSelectedItem("TIPO USUARIO");
        txtSenha.setText("2345");
        UsuariosDAO.listarUsuario("");
        UsuariosDAO.gerarId();
    }
    
    
    public void selecionarLinha(String id){
        for (int i = 0; i < tabelaUsuarios.getRowCount(); i++){
            // o segundo parametro é 0 porque indica a posição da coluna ID/código na tabela
            if (id.equals(tabelaUsuarios.getValueAt(i, 0))){
                tabelaUsuarios.setRowSelectionInterval(i, i);
                break;
            }
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCodigo = new app.bolivia.swing.JCTextField();
        codigoL = new javax.swing.JLabel();
        txtNome = new app.bolivia.swing.JCTextField();
        nomeL = new javax.swing.JLabel();
        cmbTipo = new org.bolivia.combo.SComboBoxBlue();
        lblTipo = new javax.swing.JLabel();
        cmbSexo = new org.bolivia.combo.SComboBoxBlue();
        txtSenha = new javax.swing.JPasswordField();
        lblSenha = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        nome1 = new app.bolivia.swing.JCTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnExcluirTudo = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        buscar = new app.bolivia.swing.JCTextField();
        codigoL1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Usuários");
        setPreferredSize(new java.awt.Dimension(840, 520));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "REGISTRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigo.setBackground(new java.awt.Color(34, 102, 145));
        txtCodigo.setBorder(null);
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCodigo.setOpaque(false);
        txtCodigo.setPhColor(new java.awt.Color(255, 255, 255));
        txtCodigo.setPlaceholder("CODIGO");
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 180, -1));

        codigoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/codigoL.png"))); // NOI18N
        jPanel2.add(codigoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 52));

        txtNome.setBackground(new java.awt.Color(34, 102, 145));
        txtNome.setBorder(null);
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNome.setName(""); // NOI18N
        txtNome.setOpaque(false);
        txtNome.setPhColor(new java.awt.Color(255, 255, 255));
        txtNome.setPlaceholder("NOME USUARIO");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        jPanel2.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 180, -1));

        nomeL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/nomUs.png"))); // NOI18N
        jPanel2.add(nomeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 52));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TIPO USUARIO", "ADMINISTRADOR", "PADRAO" }));
        cmbTipo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });
        jPanel2.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 183, -1));

        lblTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/tipousL.png"))); // NOI18N
        lblTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, 52));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEXO", "FEMININO", "MASCULINO" }));
        cmbSexo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel2.add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 183, -1));

        txtSenha.setBackground(new java.awt.Color(34, 102, 145));
        txtSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setToolTipText("");
        txtSenha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 170, 30));

        lblSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/senha.png"))); // NOI18N
        jPanel2.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 240, 52));

        lblSexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/sexoL.png"))); // NOI18N
        lblSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, 52));

        nome1.setBackground(new java.awt.Color(34, 102, 145));
        nome1.setBorder(null);
        nome1.setForeground(new java.awt.Color(255, 255, 255));
        nome1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nome1.setOpaque(false);
        nome1.setPhColor(new java.awt.Color(255, 255, 255));
        nome1.setPlaceholder("NOME USUARIO");
        nome1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nome1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nome1KeyTyped(evt);
            }
        });
        jPanel2.add(nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 180, -1));

        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NOME USUÁRIO", "SEXO", "TIPO", "SENHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabelaUsuarios);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "OPÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/regis1.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/regis2.png"))); // NOI18N
        btnRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnAtualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/editar.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setBorder(null);
        btnAtualizar.setBorderPainted(false);
        btnAtualizar.setContentAreaFilled(false);
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/editar1.png"))); // NOI18N
        btnAtualizar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/editar1.png"))); // NOI18N
        btnAtualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagar.png"))); // NOI18N
        btnExcluir.setBorder(null);
        btnExcluir.setBorderPainted(false);
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setLabel("Excluir");
        btnExcluir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagar1.png"))); // NOI18N
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnExcluirTudo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirTudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagarT.png"))); // NOI18N
        btnExcluirTudo.setBorder(null);
        btnExcluirTudo.setBorderPainted(false);
        btnExcluirTudo.setContentAreaFilled(false);
        btnExcluirTudo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirTudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirTudo.setLabel("Excluir Tudo");
        btnExcluirTudo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagarT1.png"))); // NOI18N
        btnExcluirTudo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluirTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTudoActionPerformed(evt);
            }
        });

        btnLimparCampos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/limpar.png"))); // NOI18N
        btnLimparCampos.setBorder(null);
        btnLimparCampos.setBorderPainted(false);
        btnLimparCampos.setContentAreaFilled(false);
        btnLimparCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparCampos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparCampos.setLabel("Limpar Campos");
        btnLimparCampos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/limpar1.png"))); // NOI18N
        btnLimparCampos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addGap(28, 28, 28)
                .addComponent(btnExcluirTudo)
                .addGap(26, 26, 26)
                .addComponent(btnLimparCampos))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtualizar)
                    .addComponent(btnRegistrar)
                    .addComponent(btnExcluir)
                    .addComponent(btnExcluirTudo)
                    .addComponent(btnLimparCampos))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "BUSCAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscar.setBackground(new java.awt.Color(34, 102, 145));
        buscar.setBorder(null);
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buscar.setOpaque(false);
        buscar.setPhColor(new java.awt.Color(255, 255, 255));
        buscar.setPlaceholder("CÓDIGO/NOME");
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });
        jPanel4.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 180, -1));

        codigoL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/buscarL.png"))); // NOI18N
        jPanel4.add(codigoL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 52));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        //Ao digitar no campo, o texto será convertido para caixa alta
        txtNome.setText(txtNome.getText().toUpperCase());
    }//GEN-LAST:event_txtNomeKeyReleased

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped

    }//GEN-LAST:event_txtNomeKeyTyped

    boolean selecionarRegistro = false;
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //se for true, quer dizer que o registro já existe no banco de dados
        if (selecionarRegistro){ 
            JOptionPane.showMessageDialog(this, "O código: " +this.txtCodigo.getText() + "\njá está registrado na base de dados", 
                    "Usuarios", 0, new ImageIcon(getClass().getResource("/imagens/principal/info.png")));
        }
        else {
            String pass = new String (txtSenha.getPassword());
            if (txtCodigo.getText().equals("") || txtNome.getText().equals("") || cmbSexo.getSelectedItem().equals("SEXO")
                    || cmbTipo.getSelectedItem().equals("TIPO USUARIO") || txtSenha.equals("")){
                JOptionPane.showMessageDialog(this, "Todos os campos \nsão \bobrigatórios!!", 
                        "Usuarios", 0, new ImageIcon(getClass().getResource("/imagens/principal/info.png")));
            }
            else {
                Usuarios us = new Usuarios();
                int cod = Integer.parseInt(txtCodigo.getText());
                us.setCodigo(cod);
                us.setNome(txtNome.getText());
                us.setSenha(pass);
                us.setSexo(cmbSexo.getSelectedItem().toString());
                us.setTipo(cmbTipo.getSelectedItem().toString());
                int opc = UsuariosDAO.cadastrar(us);
                if (opc != 0){
                    String id = txtCodigo.getText();
                    limparCampos();
                    selecionarLinha(id);
                    JOptionPane.showMessageDialog(this, "Usuário inserido com sucesso!", "Inclusão de usuário", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }     
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if (tabelaUsuarios.getRowCount() > 0){ // verifica se existem registros no BD
            if (tabelaUsuarios.getSelectedRowCount() > 0){ // verifica se existe uma linha selecionada no grid
                if (txtCodigo.getText().equals("") || txtNome.getText().equals("")
                        || txtSenha.equals("") || cmbTipo.getSelectedItem().equals("TIPO USUARIO") || cmbSexo.getSelectedItem().equals("SEXO")){
                    JOptionPane.showMessageDialog(this, "Preencha todos os \n\bcampos obrigatórios", "Campos vazios", 1);
                } else {
                    int ret = JOptionPane.showConfirmDialog(this, "Deseja realmente alterar o usuário?",
                            "Atualização de Usuário", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (ret == JOptionPane.YES_OPTION) {
                        Usuarios us = new Usuarios();
                        int codigo = Integer.parseInt(txtCodigo.getText());
                        us.setCodigo(codigo);
                        us.setNome(txtNome.getText());
                        String senha = new String(txtSenha.getPassword());
                        us.setSenha(senha);
                        us.setTipo(cmbTipo.getSelectedItem().toString());
                        us.setSexo(cmbSexo.getSelectedItem().toString());

                        int opc = UsuariosDAO.atualizar(us);
                        if (opc != 0) {
                            //Opc está carregada, logo teve atualização
                            limparCampos();
                            String id = txtCodigo.getText();
                            selecionarLinha(id);
                            selecionarRegistro = false;
                            JOptionPane.showMessageDialog(this, "Usuário atualizado com sucesso!!!",
                                    "Atualização de Usuário", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this, "Nenhum usuário selecionado", "Registro não selecionado", 1);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Banco de dados sem registros de usuários", 
                    "Erro base de usuários", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tabelaUsuarios.getRowCount() > 0){
            
            if (tabelaUsuarios.getSelectedRow() > 0) {
                int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o usuário?", 
                        "Exclusão de Usuário", JOptionPane.YES_OPTION, JOptionPane.WARNING_MESSAGE);
                if (resposta == JOptionPane.YES_OPTION){
                    int linha = tabelaUsuarios.getSelectedRow();
                    //int i = Integer.valueOf((String) object);
                    int id = Integer.valueOf((String)tabelaUsuarios.getValueAt(linha, 0)); // coluna 0 representa o código_us na tabela do BD
                    int apagar = UsuariosDAO.excluir(id);
                    if (apagar != 0){
                        limparCampos();
                        selecionarRegistro = false;
                        JOptionPane.showMessageDialog(this, "Usuário excluído", "Exclusão de Usuário", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nenhum usuário selecionado", "Registro não selecionado", 1);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Banco de dados sem registros de usuários", 
                    "Erro base de dados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnExcluirTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTudoActionPerformed
        if (tabelaUsuarios.getRowCount() > 0){
            int resposta = JOptionPane.showConfirmDialog(this, "Você realmente deseja \nexcluir \btodos os usuários?", 
                    "Exclusão de todos registros", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (resposta == JOptionPane.YES_OPTION){
                int apagarTudo = UsuariosDAO.excluirTudo();
                if (apagarTudo != 0){
                    limparCampos();
                    selecionarRegistro = false;
                    JOptionPane.showMessageDialog(this, "Todos registros excluídos", 
                            "Exclusão Geral", JOptionPane.INFORMATION_MESSAGE);
                }
            } else { 
                JOptionPane.showMessageDialog(this, "Gostaria de excluir apenas um registro?", 
                        "Exclusão de Registro", JOptionPane.QUESTION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Banco de dados sem registros de usuários", 
                    "Erro base de dados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirTudoActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked
        limparCampos();
    }//GEN-LAST:event_buscarMouseClicked

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
        buscar.setText(buscar.getText().toUpperCase());
        UsuariosDAO.listarUsuario(buscar.getText());
    }//GEN-LAST:event_buscarKeyReleased

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void nome1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nome1KeyReleased

    private void nome1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nome1KeyTyped

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirTudo;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnRegistrar;
    private app.bolivia.swing.JCTextField buscar;
    private org.bolivia.combo.SComboBoxBlue cmbSexo;
    private org.bolivia.combo.SComboBoxBlue cmbTipo;
    private javax.swing.JLabel codigoL;
    private javax.swing.JLabel codigoL1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTipo;
    private app.bolivia.swing.JCTextField nome1;
    private javax.swing.JLabel nomeL;
    public static javax.swing.JTable tabelaUsuarios;
    protected static app.bolivia.swing.JCTextField txtCodigo;
    private app.bolivia.swing.JCTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
