package produtos;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import static usuarios.FrmUsuarios.tabelaUsuarios;

/**
 *
 * @author hugov
 */
public class FrmProdutos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProdutos
     */
    public FrmProdutos() {
        initComponents();
        tabela.getTableHeader().setDefaultRenderer(new principal.EstiloTabelaHeader());
        tabela.setDefaultRenderer(Object.class, new principal.EstiloTabelaRenderer());
        // puxa um registro armazenado na tabela Produtos no banco de dados
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        limparCampos();
        
        tabela.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                //Se uma das linhas de registros for alterada, então executa a atualização de dados
                if (tabela.getSelectedRow() != -1){
                    atualizarDados();
                    selecionarRegistro = true;
                }
            }
        });
    }

    public void atualizarDados(){
        int linha = tabela.getSelectedRow();
        txtCodigo.setText(tabela.getValueAt(linha, 0).toString());
        cmbTipoProduto.setSelectedItem(tabela.getValueAt(linha, 1).toString());
        txtNome.setText(tabela.getValueAt(linha, 2).toString());
        txtPreco.setText(tabela.getValueAt(linha, 3).toString());
    }
    
    public void limparCampos(){
        if (tabela.getSelectedRow() > -1){
            tabela.removeRowSelectionInterval(tabela.getSelectedRow(), tabela.getSelectedRow());
        }
        txtCodigo.setText("");
        cmbTipoProduto.setSelectedItem("TIPO PRODUTO");
        txtNome.setText("");
        txtPreco.setText("");
        ProdutosDAO.listar("");
        ProdutosDAO.gerarID();
    }
    
    public void selecionarLinha(String id){
        for (int i = 0; i < tabela.getRowCount(); i++){
            if (id.equals(tabela.getValueAt(i, 0))){
                tabela.setRowSelectionInterval(i, i);
                break;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCodigo = new app.bolivia.swing.JCTextField();
        codigoL = new javax.swing.JLabel();
        txtNome = new app.bolivia.swing.JCTextField();
        nomeL = new javax.swing.JLabel();
        cmbTipoProduto = new org.bolivia.combo.SComboBoxBlue();
        tipoL = new javax.swing.JLabel();
        txtPreco = new app.bolivia.swing.JCTextField();
        nomeL1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnExcluirTudo = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtBusca = new app.bolivia.swing.JCTextField();
        codigoL1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(780, 520));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "REGISTRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(34, 102, 145));
        txtCodigo.setBorder(null);
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCodigo.setOpaque(false);
        txtCodigo.setPhColor(new java.awt.Color(255, 255, 255));
        txtCodigo.setPlaceholder("CÓDIGO");
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 180, -1));

        codigoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/codigoL.png"))); // NOI18N
        jPanel2.add(codigoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 52));

        txtNome.setBackground(new java.awt.Color(34, 102, 145));
        txtNome.setBorder(null);
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNome.setOpaque(false);
        txtNome.setPhColor(new java.awt.Color(255, 255, 255));
        txtNome.setPlaceholder("NOME PRODUTO");
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        jPanel2.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 180, -1));

        nomeL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/nomeL.png"))); // NOI18N
        jPanel2.add(nomeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, 52));

        cmbTipoProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TIPO PRODUTO", "BEBIDAS", "CARNES", "DOCES", "FRUTAS", "LACTINEOS", "LEGUMES", "MASSA", "SOPA", "VERDURAS" }));
        cmbTipoProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(cmbTipoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 183, -1));

        tipoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/tipopro.png"))); // NOI18N
        tipoL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(tipoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, -1, 52));

        txtPreco.setBackground(new java.awt.Color(34, 102, 145));
        txtPreco.setBorder(null);
        txtPreco.setForeground(new java.awt.Color(255, 255, 255));
        txtPreco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPreco.setOpaque(false);
        txtPreco.setPhColor(new java.awt.Color(255, 255, 255));
        txtPreco.setPlaceholder("PRECO");
        txtPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecoKeyTyped(evt);
            }
        });
        jPanel2.add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 180, -1));

        nomeL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/precoL.png"))); // NOI18N
        jPanel2.add(nomeL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, 52));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "TIPO PRODUTO", "NOME DO PRODUTO", "PREÇO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabela);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "OPÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/regis1.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(null);
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/regis2.png"))); // NOI18N
        btnRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnAtualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/editar.png"))); // NOI18N
        btnAtualizar.setBorder(null);
        btnAtualizar.setBorderPainted(false);
        btnAtualizar.setContentAreaFilled(false);
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtualizar.setLabel("Atualizar");
        btnAtualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/editar1.png"))); // NOI18N
        btnAtualizar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/editar1.png"))); // NOI18N
        btnAtualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagar.png"))); // NOI18N
        btnExcluir.setBorder(null);
        btnExcluir.setBorderPainted(false);
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setLabel("Excluir");
        btnExcluir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagar1.png"))); // NOI18N
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnExcluirTudo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirTudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagarT.png"))); // NOI18N
        btnExcluirTudo.setBorder(null);
        btnExcluirTudo.setBorderPainted(false);
        btnExcluirTudo.setContentAreaFilled(false);
        btnExcluirTudo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirTudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirTudo.setLabel("Excluir Tudo");
        btnExcluirTudo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagarT1.png"))); // NOI18N
        btnExcluirTudo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluirTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTudoActionPerformed(evt);
            }
        });

        btnLimparCampos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/limpar.png"))); // NOI18N
        btnLimparCampos.setBorder(null);
        btnLimparCampos.setBorderPainted(false);
        btnLimparCampos.setContentAreaFilled(false);
        btnLimparCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparCampos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparCampos.setLabel("Limpar Campos");
        btnLimparCampos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/limpar1.png"))); // NOI18N
        btnLimparCampos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar)
                .addGap(14, 14, 14)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirTudo)
                .addGap(18, 18, 18)
                .addComponent(btnLimparCampos)
                .addGap(4, 4, 4))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar)
            .addComponent(btnAtualizar)
            .addComponent(btnExcluir)
            .addComponent(btnExcluirTudo)
            .addComponent(btnLimparCampos)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "BUSCAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusca.setBackground(new java.awt.Color(34, 102, 145));
        txtBusca.setBorder(null);
        txtBusca.setForeground(new java.awt.Color(255, 255, 255));
        txtBusca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBusca.setOpaque(false);
        txtBusca.setPhColor(new java.awt.Color(255, 255, 255));
        txtBusca.setPlaceholder("TIPO PRODUTO/NOME");
        txtBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscaMouseClicked(evt);
            }
        });
        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });
        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaKeyReleased(evt);
            }
        });
        jPanel4.add(txtBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 180, -1));

        codigoL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/buscarL.png"))); // NOI18N
        jPanel4.add(codigoL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 52));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased

    }//GEN-LAST:event_txtNomeKeyReleased

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped

    }//GEN-LAST:event_txtNomeKeyTyped

    private void txtPrecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecoKeyTyped

    }//GEN-LAST:event_txtPrecoKeyTyped

    boolean selecionarRegistro = false;
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (selecionarRegistro){
            JOptionPane.showMessageDialog(this, "O código " + txtCodigo.getText() + " já está registrado na base de dados", 
                    "Produtos", JOptionPane.ERROR_MESSAGE);
        } else {
            if (txtCodigo.getText().equals("") || cmbTipoProduto.getSelectedItem().equals("TIPO PRODUTO") ||
                    txtNome.getText().equals("") || txtPreco.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Por favor, informe todos os \n\bcampos obrigatórios", 
                        "Campos vazios", JOptionPane.WARNING_MESSAGE);
            } else {
                Produtos produtos = new Produtos();
                produtos.setCodigo(Integer.parseInt(txtCodigo.getText()));
                produtos.setTipo(cmbTipoProduto.getSelectedItem().toString());
                produtos.setNome(txtNome.getText());
                float preco = Float.parseFloat(txtPreco.getText());
                produtos.setValor(preco);
                
                int resposta = ProdutosDAO.cadastrar(produtos);
                if (resposta != 0){
                    String cod = txtCodigo.getText();
                    limparCampos();
                    selecionarLinha(cod);
                    JOptionPane.showMessageDialog(this, "Produto inserido com sucesso!!!", 
                            "Inclusão de Produto", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    //Pendente testar a atualização de produtos pelo formulário
    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if (tabela.getRowCount() > 0){ //verifica se existem linhas no BD
            if (tabela.getSelectedRow() > 0){ //verifica se existe uma linha selecionada no grid
                if (txtCodigo.getText().equals("") || cmbTipoProduto.getSelectedItem().equals("TIPO PRODUTO") ||
                        txtNome.getText().equals("") || txtPreco.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Por favor, preencha todos os \ncampos obrigatórios", 
                            "Campos vazios", JOptionPane.INFORMATION_MESSAGE);
                } else {
                     int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente alterar o produto?", 
                            "Atualização de Produto", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                     if (resposta == JOptionPane.YES_OPTION){
                         Produtos prod = new Produtos();
                         int codigo = Integer.parseInt(txtCodigo.getText());
                         prod.setCodigo(codigo);
                         prod.setTipo(cmbTipoProduto.getSelectedItem().toString());
                         prod.setNome(txtNome.getText());
                         prod.setValor(Float.parseFloat(txtPreco.getText()));
                         int opcao = ProdutosDAO.atualizar(prod);
                         
                         if (opcao != 0){
                             String id = txtCodigo.getText();
                             limparCampos();
                             selecionarLinha(id);                         
                         }
                     }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum produto selecionado", 
                    "Produto não selecionado", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não existem registros no banco de dados", 
                    "Erro Banco de Dados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tabela.getRowCount() > 0){
            if (tabela.getSelectedRow() > 0){
                int resposta = JOptionPane.showConfirmDialog(null, "Realmente deseja excluir este produto?", 
                        "Exclusão de Produto", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (resposta == JOptionPane.YES_OPTION){
                    int linha = tabela.getSelectedRow();
                    int cod = Integer.valueOf((String)tabela.getValueAt(linha, 0));
                    int apagar = ProdutosDAO.excluir(cod);
                    if (apagar != 0){
                        limparCampos();
                        selecionarRegistro = false;
                        JOptionPane.showMessageDialog(null, "Produto excluido com sucesso", 
                                "Exclusão de Produto", JOptionPane.INFORMATION_MESSAGE);
                    }     
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum produto selecionado",
                        "Registro não selecionado", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não há registros na base de dados", 
                    "Erro Banco de Dados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnExcluirTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTudoActionPerformed
        if (tabela.getRowCount() > 0) {
            int resposta = JOptionPane.showConfirmDialog(this, "Realmente deseja excluir \ntodos os produtos?", 
                    "Exclusão de todos os registros", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (resposta == JOptionPane.YES_OPTION){
                int apagarTudo = ProdutosDAO.excluirTudo();
                if (apagarTudo != 0){
                    limparCampos();
                    selecionarRegistro = false;
                    JOptionPane.showMessageDialog(this, "Todos os registros excluídos", 
                            "Exclusão Geral", JOptionPane.INFORMATION_MESSAGE);
                }
            } else { //no caso de o usuário selecionar opção que "não" deseja excluir tudo
                JOptionPane.showMessageDialog(null, "Não gostaria de excluir apenas um produto?", 
                        "Exclusão de Registro", JOptionPane.QUESTION_MESSAGE);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Não há registros na base de dados", 
                    "Erro Banco de Dados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirTudoActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void txtBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscaMouseClicked

    }//GEN-LAST:event_txtBuscaMouseClicked

    private void txtBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyReleased
        // TODO add your handling code here:
        txtBusca.setText(txtBusca.getText().toUpperCase());
        ProdutosDAO.listar(txtBusca.getText());
    }//GEN-LAST:event_txtBuscaKeyReleased

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
    }//GEN-LAST:event_txtBuscaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirTudo;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnRegistrar;
    private org.bolivia.combo.SComboBoxBlue cmbTipoProduto;
    private javax.swing.JLabel codigoL;
    private javax.swing.JLabel codigoL1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeL;
    private javax.swing.JLabel nomeL1;
    public static javax.swing.JTable tabela;
    private javax.swing.JLabel tipoL;
    private app.bolivia.swing.JCTextField txtBusca;
    public static app.bolivia.swing.JCTextField txtCodigo;
    private app.bolivia.swing.JCTextField txtNome;
    private app.bolivia.swing.JCTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
