package vendas;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import static principal.MenuPrincipal.carregador;
import principal.Sessao;
import produtos.FrmListaProd;
import static produtos.FrmProdutos.tabela;


/**
 *
 * @author hugov
 */
public class FrmCaixa extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCaixa
     */
    //public int codigoUsuarioAtivo = Sessao.codigo;
    
    public boolean estaFechado(Object obj){
        JInternalFrame ativos[] = carregador.getAllFrames();
        boolean fechado = true;
        int i = 0;
        while (i < ativos.length && fechado){
            if (ativos[i] == obj){
                fechado = false;
            }
            i++;
        }
        return fechado;
    }
    
    public FrmCaixa() {
        initComponents();
        FrmCaixa.tabela.getTableHeader().setDefaultRenderer(new principal.EstiloTabelaHeader());
        FrmCaixa.tabela.setDefaultRenderer(Object.class, new principal.EstiloTabelaRenderer());
        // puxa um registro armazenado na tabela Vendas no banco de dados
        FrmCaixa.tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        limparCampos();
    }

    public static String gerarDataAtual(){
        Date data = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        return sdf.format(data);
    }
    
    public void limparCampos(){
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        
        while (model.getRowCount() > 0){
            model.removeRow(0);
        }
        txtData.setText("");
        txtData.setText(gerarDataAtual());
        txtRecebido.setText("");
        txtTroco.setText("");
        txtTotal.setText("0.0");
        VendasDAO.gerarNumeros();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBusca = new javax.swing.JButton();
        txtData = new app.bolivia.swing.JCTextField();
        lblData = new javax.swing.JLabel();
        txtRecebido = new app.bolivia.swing.JCTextField();
        lblRecebido = new javax.swing.JLabel();
        txtTroco = new app.bolivia.swing.JCTextField();
        lblTroco = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnVender = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        txtTotal = new app.bolivia.swing.JCTextField();
        lblTotal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtNumeroVenda = new app.bolivia.swing.JCTextField();
        lblFatura = new javax.swing.JLabel();
        lblNumeroVenda = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Caixa");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBusca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/produto1.png"))); // NOI18N
        btnBusca.setBorder(null);
        btnBusca.setContentAreaFilled(false);
        btnBusca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBusca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBusca.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/produto.png"))); // NOI18N
        btnBusca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });
        jPanel2.add(btnBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtData.setEditable(false);
        txtData.setBackground(new java.awt.Color(34, 102, 145));
        txtData.setBorder(null);
        txtData.setForeground(new java.awt.Color(255, 255, 255));
        txtData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtData.setOpaque(false);
        txtData.setPhColor(new java.awt.Color(255, 255, 255));
        txtData.setPlaceholder("DATA");
        jPanel2.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 180, -1));

        lblData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/data.png"))); // NOI18N
        jPanel2.add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, 52));

        txtRecebido.setBackground(new java.awt.Color(34, 102, 145));
        txtRecebido.setBorder(null);
        txtRecebido.setForeground(new java.awt.Color(255, 255, 255));
        txtRecebido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRecebido.setOpaque(false);
        txtRecebido.setPhColor(new java.awt.Color(255, 255, 255));
        txtRecebido.setPlaceholder("RECEBIDO");
        jPanel2.add(txtRecebido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 130, -1));

        lblRecebido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/recibi.png"))); // NOI18N
        lblRecebido.setToolTipText("RECIBI");
        jPanel2.add(lblRecebido, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 52));

        txtTroco.setEditable(false);
        txtTroco.setBackground(new java.awt.Color(34, 102, 145));
        txtTroco.setBorder(null);
        txtTroco.setForeground(new java.awt.Color(255, 255, 255));
        txtTroco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTroco.setOpaque(false);
        txtTroco.setPhColor(new java.awt.Color(255, 255, 255));
        txtTroco.setPlaceholder("TROCO");
        jPanel2.add(txtTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 130, -1));

        lblTroco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/valores.png"))); // NOI18N
        lblTroco.setToolTipText("CAMBIO");
        jPanel2.add(lblTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, 52));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "OPÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/calculo1.png"))); // NOI18N
        btnCalcular.setBorder(null);
        btnCalcular.setContentAreaFilled(false);
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalcular.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/calculo2.png"))); // NOI18N
        btnCalcular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnVender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/venda1.png"))); // NOI18N
        btnVender.setBorder(null);
        btnVender.setContentAreaFilled(false);
        btnVender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVender.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/venda2.png"))); // NOI18N
        btnVender.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/elimina1.png"))); // NOI18N
        btnExcluir.setBorder(null);
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/elimina2.png"))); // NOI18N
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/cancela1.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/cancela2.png"))); // NOI18N
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcular)
                    .addComponent(btnVender)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "TIPO PRODUTO", "DESCRIÇÃO", "VALOR", "QUANTIDADE", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabela);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 790, 200));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(34, 102, 145));
        txtTotal.setBorder(null);
        txtTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal.setOpaque(false);
        txtTotal.setPhColor(new java.awt.Color(255, 255, 255));
        txtTotal.setPlaceholder("TOTAL");
        jPanel4.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 80, 30));

        lblTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/total.png"))); // NOI18N
        jPanel4.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, -1, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/logomenor.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("COMÉRCIO BIGUZZI SANTELLO LTDA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TELEFONES:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("11 97527-5084");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("11 97527-5084");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumeroVenda.setEditable(false);
        txtNumeroVenda.setBackground(new java.awt.Color(34, 102, 145));
        txtNumeroVenda.setBorder(null);
        txtNumeroVenda.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroVenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNumeroVenda.setOpaque(false);
        txtNumeroVenda.setPhColor(new java.awt.Color(255, 255, 255));
        txtNumeroVenda.setPlaceholder("FATURA");
        jPanel6.add(txtNumeroVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 130, 30));

        lblFatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/numFac.png"))); // NOI18N
        jPanel6.add(lblFatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 50));

        lblNumeroVenda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNumeroVenda.setText("NÚMERO DE VENDA");
        jPanel6.add(lblNumeroVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        lblNumeroVenda.getAccessibleContext().setAccessibleName("NÚMERO DA VENDA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    produtos.FrmListaProd lista;
    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        if (estaFechado(lista)){
            lista = new FrmListaProd();
            principal.MenuPrincipal.carregador.add(lista);
            lista.toFront();
            lista.setVisible(true);
        } else {
            //quer dizer que o formulário já está aberto
            lista.toFront();
        }
           
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if (tabela.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Informe, pelo menos, um produto", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (txtRecebido.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Insira um valor monetário no campo Recebido", "Cobrança", JOptionPane.WARNING_MESSAGE);
        } else {
            //foi inserido um valor válido
            float valorRecebido = Float.parseFloat(txtRecebido.getText());
            float valorTotal = Float.parseFloat(txtTotal.getText());
            
            if (valorRecebido < valorTotal){
                JOptionPane.showMessageDialog(null, "Valor insuficiente para essa transação", "Erro", JOptionPane.ERROR_MESSAGE);
            } else {
                float troco = valorRecebido - valorTotal;
                DecimalFormat formato = new DecimalFormat("#.##");
                txtTroco.setText(String.valueOf(formato.format(troco)));
            }
            
        }     
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        if (tabela.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Erro ao realizar venda\nNão existem produtos no caixa", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else if (txtRecebido.getText().equals("") || txtRecebido.getText().equals(null)){
            JOptionPane.showMessageDialog(null, "É necessário efetuar o pagamento das compras", 
                    "Efetue o Pagamento", JOptionPane.ERROR_MESSAGE);
        }
        else {
            float valorRecebido = Float.parseFloat(txtRecebido.getText());
            float valorTotal = Float.parseFloat(txtTotal.getText());
            if (valorTotal > valorRecebido){
                JOptionPane.showMessageDialog(null, "Valor insuficiente para essa transação.\nInsira novamente o valor",
                        "ERRO", JOptionPane.ERROR_MESSAGE);
            } else {
                Vendas venda = new Vendas();
                venda.setCodigo_venda(Integer.parseInt(txtNumeroVenda.getText()));
                venda.setTotal_venda(Float.parseFloat(txtTotal.getText()));
                venda.setData_venda(txtData.getText());
                int idSessaoUsuario = Sessao.armazenarIdUsuario(Sessao.usuario);
                venda.setId_usuario(idSessaoUsuario);

                int acao = VendasDAO.cadastrar(venda);
                if (acao != 0) {
                    limparCampos();
                    JOptionPane.showMessageDialog(null, "Venda efetuada com sucesso", "VENDA", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tabela.getRowCount() > 0){
            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
            int linha = tabela.getSelectedRow();
            if (linha > 0){
                modelo.removeRow(linha);
                FrmListaProd listaProd = new FrmListaProd();
                listaProd.calcular();
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um produto para excluir", 
                        "Registro não selecionado", JOptionPane.WARNING_MESSAGE);
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Não há produtos no caixa", 
                    "Erro ao efetuar a exclusão", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFatura;
    private javax.swing.JLabel lblNumeroVenda;
    private javax.swing.JLabel lblRecebido;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTroco;
    public static javax.swing.JTable tabela;
    private app.bolivia.swing.JCTextField txtData;
    public static app.bolivia.swing.JCTextField txtNumeroVenda;
    public static app.bolivia.swing.JCTextField txtRecebido;
    public static app.bolivia.swing.JCTextField txtTotal;
    public static app.bolivia.swing.JCTextField txtTroco;
    // End of variables declaration//GEN-END:variables
}
