package vendas;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import usuarios.UsuariosDAO;

/**
 *
 * @author hugov
 */
public class FrmVendas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmVendas
     */
    public FrmVendas() {
        initComponents();
        tabela.getTableHeader().setDefaultRenderer(new principal.EstiloTabelaHeader());
        tabela.setDefaultRenderer(Object.class, new principal.EstiloTabelaRenderer());
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        limparCampos();
    }

    public void limparCampos(){
        if (tabela.getSelectedRow() > -1){
            tabela.removeRowSelectionInterval(tabela.getSelectedRow(), tabela.getSelectedRow());
        }
        dateData.setDate(null);
        txtBuscar.setText("");
        VendasDAO.listarVendasCliente("");
        
    }
    
    /*public int identificarCliente(){
        
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtBuscar = new app.bolivia.swing.JCTextField();
        btnExcluir = new javax.swing.JButton();
        btnExcluirTudo = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        btnBuscarPorData = new javax.swing.JButton();
        lblData = new javax.swing.JLabel();
        btnVendasHoje = new javax.swing.JButton();
        dateData = new com.toedter.calendar.JDateChooser();
        codigoL2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Lista de Vendas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NÚMERO VENDA", "TOTAL", "DATA", "CLIENTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabela);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "OPÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setBackground(new java.awt.Color(34, 102, 145));
        txtBuscar.setBorder(null);
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtBuscar.setOpaque(false);
        txtBuscar.setPhColor(new java.awt.Color(255, 255, 255));
        txtBuscar.setPlaceholder("NÚMERO VENDA/CLIENTE");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel4.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 180, -1));

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagar.png"))); // NOI18N
        btnExcluir.setText("Eliminar");
        btnExcluir.setBorder(null);
        btnExcluir.setBorderPainted(false);
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagar1.png"))); // NOI18N
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel4.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        btnExcluirTudo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirTudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagarT1.png"))); // NOI18N
        btnExcluirTudo.setText("Eliminar Tudo");
        btnExcluirTudo.setBorder(null);
        btnExcluirTudo.setBorderPainted(false);
        btnExcluirTudo.setContentAreaFilled(false);
        btnExcluirTudo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirTudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirTudo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/apagarT1.png"))); // NOI18N
        btnExcluirTudo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluirTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTudoActionPerformed(evt);
            }
        });
        jPanel4.add(btnExcluirTudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        btnLimparCampos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/limpar.png"))); // NOI18N
        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.setBorder(null);
        btnLimparCampos.setBorderPainted(false);
        btnLimparCampos.setContentAreaFilled(false);
        btnLimparCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimparCampos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparCampos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/limpar1.png"))); // NOI18N
        btnLimparCampos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });
        jPanel4.add(btnLimparCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        btnBuscarPorData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscarPorData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/buscaF1.png"))); // NOI18N
        btnBuscarPorData.setToolTipText("Buscar");
        btnBuscarPorData.setBorder(null);
        btnBuscarPorData.setBorderPainted(false);
        btnBuscarPorData.setContentAreaFilled(false);
        btnBuscarPorData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarPorData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarPorData.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/buscaF2.png"))); // NOI18N
        btnBuscarPorData.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarPorData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorDataActionPerformed(evt);
            }
        });
        jPanel4.add(btnBuscarPorData, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        lblData.setForeground(new java.awt.Color(153, 153, 153));
        lblData.setText("Data");
        jPanel4.add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 30, -1));

        btnVendasHoje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVendasHoje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/vendasH.png"))); // NOI18N
        btnVendasHoje.setToolTipText("Buscar");
        btnVendasHoje.setBorder(null);
        btnVendasHoje.setBorderPainted(false);
        btnVendasHoje.setContentAreaFilled(false);
        btnVendasHoje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVendasHoje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVendasHoje.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/vendasH1.png"))); // NOI18N
        btnVendasHoje.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVendasHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasHojeActionPerformed(evt);
            }
        });
        jPanel4.add(btnVendasHoje, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        dateData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dateData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateDataMouseClicked(evt);
            }
        });
        jPanel4.add(dateData, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 150, 30));

        codigoL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/buscarL.png"))); // NOI18N
        jPanel4.add(codigoL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 260, 52));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        VendasDAO.listarVendasCliente(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tabela.getRowCount() > 0){
            if (tabela.getSelectedRow() > 0){
                int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir a venda?", 
                        "Confirmação exclusão venda", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (resposta == JOptionPane.YES_OPTION){
                    int linha = tabela.getSelectedRow();
                    //int id = (int) tabela.getValueAt(linha, 0);
                    int id = Integer.valueOf((String)tabela.getValueAt(linha, 0));
                    int excluir = VendasDAO.excluir(id);
                    if (excluir != 0 ){
                        limparCampos();
                        JOptionPane.showMessageDialog(this, "Venda excluída com sucesso", 
                                "Exclusão de venda", JOptionPane.INFORMATION_MESSAGE);
                    }    
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um registro para excluir", 
                        "Exclusão de Venda", JOptionPane.ERROR_MESSAGE);
            } 
        } else {
            JOptionPane.showMessageDialog(this, "Não há registros de vendas na tabela", 
                    "Sem registros na Base", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnExcluirTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTudoActionPerformed
        if (tabela.getRowCount() > 0){
            int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir\n\btodos\b os registros de vendas?", "Confirmação exclusão vendas",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE );
            if (resposta == JOptionPane.YES_OPTION){
                int excluirTudo = VendasDAO.excluirTudo();
                if (excluirTudo != 0){
                    limparCampos();
                    JOptionPane.showMessageDialog(this, "Todas as vendas excluídas com sucesso",
                            "Exclusão de vendas", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não há registros de vendas na tabela", 
                    "Sem registros na Base", JOptionPane.WARNING_MESSAGE);
        }    
    }//GEN-LAST:event_btnExcluirTudoActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
       limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnBuscarPorDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorDataActionPerformed
        if (dateData.getDate() == null){
            VendasDAO.listarVendasCliente("");
        } else {
            // usuário preencheu o filtro data
            String formato = dateData.getDateFormatString();
            Date data = dateData.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(formato);
            VendasDAO.listarPorData(sdf.format(data));
        }
        
    }//GEN-LAST:event_btnBuscarPorDataActionPerformed

    private void btnVendasHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasHojeActionPerformed
        Date dataSistema = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String faturamentoHoje = sdf.format(dataSistema);
        VendasDAO.listarPorData(faturamentoHoje);
        dateData.setDate(null);
    }//GEN-LAST:event_btnVendasHojeActionPerformed

    private void dateDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateDataMouseClicked
        // TODO add your handling code here:
        dateData.setDate(null);
        VendasDAO.listarVendasCliente("");
    }//GEN-LAST:event_dateDataMouseClicked

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPorData;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirTudo;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnVendasHoje;
    private javax.swing.JLabel codigoL2;
    private com.toedter.calendar.JDateChooser dateData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    public static javax.swing.JTable tabela;
    private app.bolivia.swing.JCTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
